version: '2'
services:
  web:
    build: ./docker/apache
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
